version: 2
updates:
- package-ecosystem: npm
  versioning-strategy: increase
  directory: "/"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "all"
  commit-message:
    prefix: "chore:"
  assignees:
    - "AdeAttwood"
  labels:
    - "priority: normal"
    - "status: to do"
    - "type: task"
    - "component: dependencies"
