name: Conventional Tools Commitlint

on:
  push: { branches: ["0.x"] }
  pull_request: { branches: ["0.x"] }

jobs:
  commits:
    name: Commitlint
    runs-on: ubuntu-latest
    container: registry.k1.zportal.co.uk/practically-oss/conventional-tools:1.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: {fetch-depth: 1000}

      - name: Lint commits
        run: conventional-tools commitlint -l1
